# Generated by Django 5.2.6 on 2025-09-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xizmatlar',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='xizmatlar',
            name='desc_en',
        ),
        migrations.RemoveField(
            model_name='xizmatlar',
            name='desc_ru',
        ),
        migrations.RemoveField(
            model_name='xizmatlar',
            name='desc_uz',
        ),
    ]
