# Generated by Django 5.2.6 on 2025-09-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_xizmatlar_desc_remove_xizmatlar_desc_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xizmatvariant',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xizmatvariant',
            name='desc_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xizmatvariant',
            name='desc_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xizmatvariant',
            name='desc_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
